// English starter sentences for the 🎲 button (spec §10): short, silly, family-friendly, drawable.
export const en: readonly string[] = [
  'A grandma winning a scooter race',
  'A walrus learning to ride a unicycle',
  'A plumber rescuing a rubber goose',
  'A wrestler who is afraid of a tiny moth',
  'A toddler driving a bulldozer',
  'A raccoon hosting a fancy tea party',
  'A lemur baking a wobbly trifle',
  'A mummy unwrapping a parcel',
  'A yak who only drinks smoothies',
  'A centaur trying on four sneakers',
  'A superhero doing the laundry',
  'A lobster playing the banjo',
  'A sheriff chasing a runaway pram',
  'An ostrich hiding in a laundry basket',
  'A kitten conducting an orchestra',
  'A kraken on a beach holiday',
  'A troll collecting stamps',
  'A pelican with far too much in its beak',
  'A princess repairing a tractor',
  'A pony in a tutu',
  'An ogre sipping cocoa in a hammock',
  'A queen who can’t find her tiara',
  'A knight riding a tricycle into battle',
  'A genie stuck in a jam jar',
  'A ferret in a sombrero playing the tuba',
  'A slug in a terrible hurry',
  'A rhino on a seesaw with a gerbil',
  'A puffin directing traffic',
  'A zombie at a tango lesson',
  'A grandpa riding a runaway lawnmower',
  'A sphinx telling terrible jokes',
  'A crow stealing the last croissant',
  'An alpaca with a wonky haircut',
  'An eel tangled in a garland',
  'A goose chasing a referee',
  'A cheetah losing a race to a slug',
  'A chameleon who can’t pick a colour',
  'A rooster who overslept',
  'A koala riding in a hot-air balloon',
  'A badger, an otter and a mole playing cards',
  'A vulture at a buffet',
  'A falcon delivering a parcel',
  'A captain steering a canoe through a puddle',
  'A newt wearing a monocle',
  'A jaguar in a tuxedo',
  'A lynx learning to whistle',
  'A gazelle on rollerskates',
  'A buffalo in a china shop',
  'A wasp with a tiny harp',
  'A bison at the bakery',
  'A moth in love with a lantern',
  'A goblin lost in a long tunnel',
  'A stork lost at the funfair',
  'A hyena who can’t stop giggling',
  'A coyote counting raisins',
  'A goat in a gondola',
  'A raven reading someone’s diary',
  'A mayor sliding down a banister',
  'A magpie stealing a shiny medal',
  'An elk on an escalator',
  'An oyster guarding a secret treasure',
  'A stingray flying a glider',
  'A vet giving a moose a check-up',
  'A janitor mopping up a lake',
  'A tailor measuring a very tall troll',
  'A hamster in a hovercraft',
  'A weasel in wellies jumping in puddles',
  'A dumpling with tiny legs',
  'A bagel going on a cruise',
  'A pickle in pyjamas',
  'A grumpy lettuce in a race',
  'A coconut playing the bongos',
  'A garlic clove scaring a vampire',
  'A peanut lifting weights',
  'A noodle escaping from the soup',
  'A cucumber on a crowded tram',
  'A radish wearing a beret',
  'A librarian shushing a thunderstorm',
  'An inventor testing a flying wardrobe',
  'A tourist taking a photo of a yeti',
  'A spy hiding behind a hedge',
  'A nanny pushing a stroller full of kittens',
  'A gardener growing a giant turnip',
  'A choir of tiny gnomes',
  'A worm going to a job interview',
  'An acrobat balancing on a melon',
  'A mime stuck in an invisible lift',
  'An emu at a sleepover',
  'An explorer discovering a lost sandpit',
  'A blizzard inside a freezer',
  'A comet that forgot where it was going',
  'A swan doing ballet on ice',
  'A puppy with a jetpack',
  'A galaxy made of sprinkles',
  'A gorilla giving a speech to a crowd',
  'A sleepy panda drinking coffee',
  'A blimp powered by soda',
  'A cactus at a balloon party',
  'A chick crossing the finish line',
  'A llama stuck in traffic',
];
