import { defineTokens } from '@pandacss/dev';

// The siblings' palette (dark): Radix "sand" greys, with Telephone Table's own accent, Radix "iris"
// (ballpoint ink, for a game played in notebooks), and the notebooks' paper.
export const tokens = defineTokens({
  fonts: {
    body: { value: 'Lato, ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif' },
    mono: { value: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace' },
    emoji: { value: '"Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", sans-serif' },
  },
  colors: {
    sand: {
      1: { value: '#111110' },
      2: { value: '#191918' },
      3: { value: '#222221' },
      4: { value: '#2A2A28' },
      5: { value: '#31312E' },
      6: { value: '#3B3A37' },
      7: { value: '#494844' },
      8: { value: '#62605B' },
      9: { value: '#6F6D66' },
      10: { value: '#7C7B74' },
      11: { value: '#B5B3AD' },
      12: { value: '#EEEEEC' },
    },
    iris: {
      1: { value: '#13131E' },
      2: { value: '#171625' },
      3: { value: '#202248' },
      4: { value: '#262A65' },
      5: { value: '#303374' },
      6: { value: '#3D3E82' },
      7: { value: '#4A4A95' },
      8: { value: '#5958B1' },
      9: { value: '#5B5BD6' },
      10: { value: '#6E6ADE' },
      11: { value: '#B1A9FF' },
      12: { value: '#E0DFFE' },
    },
    status: {
      red: { value: '#E5484D' },
      green: { value: '#30A46C' },
    },
    // The drawing inks (protocol `inkColors`, same order). The board painter reads them with `token()`.
    ink: {
      black: { value: '#111111' },
      charcoal: { value: '#4A4A4A' },
      gray: { value: '#8C8C8C' },
      silver: { value: '#CACACA' },
      white: { value: '#FFFFFF' },
      red: { value: '#E5383B' },
      orange: { value: '#F28C28' },
      yellow: { value: '#F7D038' },
      lime: { value: '#9BD143' },
      green: { value: '#2E9E4F' },
      teal: { value: '#18A999' },
      sky: { value: '#4CB5F5' },
      blue: { value: '#2F5BD8' },
      violet: { value: '#8A4FD8' },
      pink: { value: '#EE6FA8' },
      brown: { value: '#8B5A2B' },
    },
    // A notebook's page: warm paper, ruled lines, a red margin, and tape for drawings (spec D15).
    notebook: {
      paper: { value: '#FBF8F1' },
      paperShade: { value: '#EFE9DC' },
      ink: { value: '#26251F' },
      muted: { value: '#7A756A' },
      rule: { value: '#DCE3EC' },
      margin: { value: '#F0B9B4' },
      bubble: { value: '#FFFFFF' },
      tape: { value: 'rgba(244, 222, 130, 0.78)' },
      spiral: { value: '#A9A499' },
      heart: { value: '#E5484D' },
      heartTint: { value: '#FFE4E4' },
      star: { value: '#F2B53A' },
    },
    medal: {
      gold: { value: '#F2C14E' },
      silver: { value: '#C3C9D1' },
      bronze: { value: '#CD8B5A' },
    },
    player: {
      raspberry: { value: '#E01E5A' },
      sky: { value: '#1D9BD1' },
      green: { value: '#2EB67D' },
      mustard: { value: '#ECB22E' },
      violet: { value: '#8E5BD9' },
      orange: { value: '#F2711C' },
      teal: { value: '#0FA3A3' },
      pink: { value: '#E255A1' },
      lime: { value: '#7CB342' },
      indigo: { value: '#4F6BED' },
    },
  },
});
